# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=Swinject.xcodeproj
    - IOS_SDK=iphonesimulator10.0
    - OSX_SDK=macosx10.12
    - TVOS_SDK=appletvsimulator10.0
    - WATCHOS_SDK=watchsimulator3.0
  matrix:
## The iOS 8.1 simulator is commented out because it does not start. It looks a problem of the simulator.
## Uncomment the following line after the simulator problem is fixed.
#    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=9.3,name=iPhone 6" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=10.0,name=iPhone 6S Plus" SCHEME="Swinject-iOS" SDK="$IOS_SDK" PLATFORM="iOS" POD_LINT="YES" ACTION="test"
    - DESTINATION="arch=x86_64" SCHEME="Swinject-OSX" SDK="$OSX_SDK" PLATFORM="Mac" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=9.2,name=Apple TV 1080p" SCHEME="Swinject-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=10.0,name=Apple TV 1080p" SCHEME="Swinject-tvOS" SDK="$TVOS_SDK" PLATFORM="tvOS" POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="Swinject-watchOS" SDK="$WATCHOS_SDK" PLATFORM="watchOS" POD_LINT="NO" ACTION="build"
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="Swinject-watchOS" SDK="$WATCHOS_SDK" PLATFORM="watchOS" POD_LINT="NO" ACTION="build"
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.17.2/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - carthage bootstrap --verbose --no-build --use-submodules
script:
  - set -o pipefail
  - xcodebuild -version
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Release ENABLE_TESTABILITY=YES ONLY_ACTIVE_ARCH=NO $ACTION
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
notifications:
  email:
    on_success: never
